using System;
using System.Collections.Generic;
using System.IO.Abstractions;
using System.Net.Mail;
using System.Net.Mime;

namespace CricketCLI
{
    internal static class Email
    {
        public static void WriteEmail(
            IFileSystem fileSystem, 
            string smtpAuthUser, 
            string smtpAuthPassword, 
            string subject, 
            List<string> toAddresses, 
            List<string> attachmentFileNames)
        {
            try{
            MailMessage newMail = new MailMessage();
            SmtpClient client = new SmtpClient("smtp.gmail.com");
            newMail.From = new MailAddress(smtpAuthUser);
            foreach(var toAddress in toAddresses)
            {
                newMail.To.Add(toAddress);
            }
            newMail.Subject = subject;
            newMail.IsBodyHtml = true;
            newMail.Body="<h1>Cricket Statistics</h1><p>Statistics generated page is attached to this email.</p><h1>Autogenerated by CricketCLI console app on my mac.</h1>";
            
            foreach(var file in attachmentFileNames)
            {
                Attachment data = new Attachment(file, MediaTypeNames.Application.Octet);

                // Add time stamp information for the file.
                ContentDisposition disposition = data.ContentDisposition;
                disposition.CreationDate = fileSystem.File.GetCreationTime(file);
                disposition.ModificationDate = fileSystem.File.GetLastWriteTime(file);
                disposition.ReadDate = fileSystem.File.GetLastAccessTime(file);

                // Add the file attachment to this email message.
                newMail.Attachments.Add(data);
            }
            client.EnableSsl = true;
            client.Port = 587;
            client.Credentials = new System.Net.NetworkCredential(smtpAuthUser, smtpAuthPassword);
            client.Send(newMail);
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}